resources:
- repo: self

queue:
  name: Hosted VS2017

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: SnowShovel.sln
    arguments: '/v:d'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: 'tests/SnowShovel.Tests/SnowShovel.Tests.csproj'
    arguments: '-c Release'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: src/SnowShovel/SnowShovel.csproj
    buildProperties: 'Configuration=Release;BuildNumber=$(Build.BuildNumber)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: SnowShovel'
  inputs:
    artifactName: 'SnowShovel'


